/**
 * generated by Xtext 2.37.0
 */
package gameOfLife.model.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GDSLIdeModule extends AbstractGDSLIdeModule {
}
