/**
 * generated by Xtext 2.37.0
 */
package gameOfLife.model.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class GDSLDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
