/**
 * generated by Xtext 2.37.0
 */
package gameOfLife.model.gameOfLife;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameOfLife.model.gameOfLife.Cell#getX <em>X</em>}</li>
 *   <li>{@link gameOfLife.model.gameOfLife.Cell#getY <em>Y</em>}</li>
 *   <li>{@link gameOfLife.model.gameOfLife.Cell#getState <em>State</em>}</li>
 * </ul>
 *
 * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getCell()
 * @model
 * @generated
 */
public interface Cell extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getCell_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link gameOfLife.model.gameOfLife.Cell#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getCell_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link gameOfLife.model.gameOfLife.Cell#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>State</b></em>' attribute.
   * The literals are from the enumeration {@link gameOfLife.model.gameOfLife.CellState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' attribute.
   * @see gameOfLife.model.gameOfLife.CellState
   * @see #setState(CellState)
   * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getCell_State()
   * @model
   * @generated
   */
  CellState getState();

  /**
   * Sets the value of the '{@link gameOfLife.model.gameOfLife.Cell#getState <em>State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' attribute.
   * @see gameOfLife.model.gameOfLife.CellState
   * @see #getState()
   * @generated
   */
  void setState(CellState value);

} // Cell
