/**
 * generated by Xtext 2.37.0
 */
package gameOfLife.model.gameOfLife;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameOfLife.model.gameOfLife.Model#getCells <em>Cells</em>}</li>
 *   <li>{@link gameOfLife.model.gameOfLife.Model#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Cells</b></em>' containment reference list.
   * The list contents are of type {@link gameOfLife.model.gameOfLife.Cell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cells</em>' containment reference list.
   * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getModel_Cells()
   * @model containment="true"
   * @generated
   */
  EList<Cell> getCells();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameOfLife.model.gameOfLife.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getModel_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // Model
