/**
 * generated by Xtext 2.37.0
 */
package gameOfLife.model.gameOfLife;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameOfLife.model.gameOfLife.Rule#getCondition <em>Condition</em>}</li>
 *   <li>{@link gameOfLife.model.gameOfLife.Rule#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getRule_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link gameOfLife.model.gameOfLife.Rule#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see gameOfLife.model.gameOfLife.GameOfLifePackage#getRule_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link gameOfLife.model.gameOfLife.Rule#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

} // Rule
