/**
 * generated by Xtext 2.37.0
 */
package gameOfLife.model;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GDSLStandaloneSetup extends GDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new GDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
